on:
  # Trigger analysis when pushing to your main branches, and when creating a pull request.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: Main Workflow
jobs:
  sonarqube:
    name: SonarQube Scan
    uses: ./.github/workflows/workflow-sonarqube.yaml
    secrets: inherit
    
